[package]
name = "tvinoferma"
version = "0.1.0"
description = "Менеджер персонажей Твинофермы"
authors = ["#Дреднайт"]
edition = "2021"

[lib]
name = "tvinoferma_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2" 
