name: Add to project

# Необязательно. Автоматически добавляет новые Issues в GitHub Project.
# Нужен секрет ADD_TO_PROJECT_PAT (personal access token с правом "project") и правильный URL проекта.
on:
  issues:
    types: [opened, transferred]

jobs:
  add:
    runs-on: ubuntu-latest
    if: ${{ vars.PROJECT_URL != '' }}
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
